// Firestore collection names (single source of truth)
export const COLLECTIONS = {
  users: "users",
  categories: "categories",
  courses: "courses",
  sections: "sections",
  reviews: "reviews",
  enrollments: "enrollments",
  liveSessions: "liveSessions",
  payments: "payments",
  coupons: "coupons",
  certificates: "certificates",
  certificateTemplates: "certificateTemplates",
  assignments: "assignments",
  assignmentSubmissions: "assignmentSubmissions",
  supportTickets: "supportTickets",
  referralEarnings: "referralEarnings",
  referralWallets: "referralWallets",
  referralWithdrawals: "referralWithdrawals",
  auditLogs: "auditLogs",
  testimonials: "testimonials",
  announcements: "announcements",
  notifications: "notifications",
} as const
